//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragatiYarn.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllMaterial
    {
        public AllMaterial()
        {
            this.Sales = new HashSet<Sale>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int MaterialId { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialImagePath { get; set; }
        public Nullable<int> MaterialTypeId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Sub_KasabId { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual Sub_Kasab Sub_Kasab { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
