//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragatiYarn.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerPaidHistories = new HashSet<CustomerPaidHistory>();
            this.CustomerPayableAmounts = new HashSet<CustomerPayableAmount>();
            this.Invoices = new HashSet<Invoice>();
            this.MonthlyInvoices = new HashSet<MonthlyInvoice>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerSurname { get; set; }
        public string CustomerName { get; set; }
        public string CustomerFirmname { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public string CustomerImageName { get; set; }
        public string CustomerImagePath { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<CustomerPaidHistory> CustomerPaidHistories { get; set; }
        public virtual ICollection<CustomerPayableAmount> CustomerPayableAmounts { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<MonthlyInvoice> MonthlyInvoices { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
