//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragatiYarn.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PragatiEntities : DbContext
    {
        public PragatiEntities()
            : base("name=PragatiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AllMaterial> AllMaterials { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerPaidHistory> CustomerPaidHistories { get; set; }
        public DbSet<CustomerPayableAmount> CustomerPayableAmounts { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<MaterialType> MaterialTypes { get; set; }
        public DbSet<MonthlyInvoice> MonthlyInvoices { get; set; }
        public DbSet<Stock> Stocks { get; set; }
        public DbSet<Sub_Accralic> Sub_Accralic { get; set; }
        public DbSet<Sub_FizingPaper> Sub_FizingPaper { get; set; }
        public DbSet<Sub_Kasab> Sub_Kasab { get; set; }
        public DbSet<SubMaterialType> SubMaterialTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Sale> Sales { get; set; }
    }
}
