//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragatiYarn.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public Nullable<int> Nos_Of_Piece { get; set; }
        public Nullable<float> Tot_Weight_in_Gram_ { get; set; }
        public string CreatedDateTime { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<float> TotalAmount { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string ReturnPiece { get; set; }
    
        public virtual AllMaterial AllMaterial { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual User User { get; set; }
    }
}
