//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragatiYarn.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int StockId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> Nos_Of_Piece { get; set; }
        public Nullable<float> Tot_Weight_in_Gram_ { get; set; }
        public string LastAddedStock { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public Nullable<int> SubMaterialTypeId { get; set; }
        public Nullable<int> MaterialTypeId { get; set; }
        public Nullable<int> Sub_KasabId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual AllMaterial AllMaterial { get; set; }
        public virtual MaterialType MaterialType { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Sub_Kasab Sub_Kasab { get; set; }
        public virtual SubMaterialType SubMaterialType { get; set; }
        public virtual User User { get; set; }
    }
}
