//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PragatiYarn.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.CustomerPaidHistories = new HashSet<CustomerPaidHistory>();
            this.CustomerPayableAmounts = new HashSet<CustomerPayableAmount>();
            this.Invoices = new HashSet<Invoice>();
            this.MonthlyInvoices = new HashSet<MonthlyInvoice>();
            this.Stocks = new HashSet<Stock>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int UserId { get; set; }
        public string Fullname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<CustomerPaidHistory> CustomerPaidHistories { get; set; }
        public virtual ICollection<CustomerPayableAmount> CustomerPayableAmounts { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<MonthlyInvoice> MonthlyInvoices { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
